const NOTE_COMPLETION = "NOTE_COMPLETION";
const TABLE_COMPLETION = "TABLE_COMPLETION";
const SINGLE_MULTIPLE_CHOICE = "SINGLE_MULTIPLE_CHOICE";
const MULTIPLE_MULTIPLE_CHOICES = "MULTIPLE_MULTIPLE_CHOICES";
const MATCH_ITEM = "MATCH_ITEM";
const LABEL_MAP = "LABEL_MAP";

export {
    NOTE_COMPLETION,
    TABLE_COMPLETION,
    SINGLE_MULTIPLE_CHOICE,
    MULTIPLE_MULTIPLE_CHOICES,
    MATCH_ITEM,
    LABEL_MAP
};