/**
 * All the reading question types in IELTS
 */

const SINGLE_MULTIPLE_CHOICE = "SINGLE_MULTIPLE_CHOICE";
const TRUE_FALSE_NOT_GIVEN = "TRUE_FALSE_NOT_GIVEN";
const MATCH_HEADINGS = "MATCH_HEADINGS";
const MULTIPLE_MULTIPLE_CHOICES = "MULTIPLE_MULTIPLE_CHOICES";
const NOTE_COMPLETION = "NOTE_COMPLETION";
const SUMMARY_COMPLETION = "SUMMARY_COMPLETION";
const FLOWCHART_COMPLETION = "FLOWCHART_COMPLETION";
const SENTENCE_COMPLETION = "SENTENCE_COMPLETION";
const MATCH_PARAGRAPH = "MATCH_PARAGRAPH";
const SUMMARY_COMPLETION_CHOICE = "SUMMARY_COMPLETION_CHOICE";
const MATCH_STATEMENT = "MATCH_STATEMENT";

export {
    SINGLE_MULTIPLE_CHOICE,
    TRUE_FALSE_NOT_GIVEN,
    MATCH_HEADINGS,
    MULTIPLE_MULTIPLE_CHOICES,
    NOTE_COMPLETION,
    SUMMARY_COMPLETION,
    FLOWCHART_COMPLETION,
    SENTENCE_COMPLETION,
    MATCH_PARAGRAPH,
    SUMMARY_COMPLETION_CHOICE,
    MATCH_STATEMENT
}